import { ChildData } from './types';

export const childrenData: ChildData[] = [
  {
    id: 1,
    nik: "3506094207090001",
    nomor: "3506091312102620",
    namaLengkap: "AURELIA SAKURA SALSABILA",
    tempatLahir: "Kediri",
    tanggalLahir: "7/2/2009",
    umur: 16,
    jenisKelamin: "Perempuan",
    agama: "Islam",
    kecamatan: "Plosoklaten",
    kelurahan: "Gondang",
    alamat: "Dusun Sema",
    rt: "018",
    rw: "004",
    anakKe: 1,
    jumlahSaudara: 2,
    namaAyah: "Nasrodin",
    namaIbu: "Sri Sukasih",
    ukuranBaju: "M",
    ukuranSepatu: 38,
    waliAsuh: "Bu Erna & Eko Wahyudi"
  },
  {
    id: 2,
    nik: "3506096502100001",
    nomor: "3506092509120001",
    namaLengkap: "LAILA FEBRI NUR FATIN",
    tempatLahir: "KEDIRI",
    tanggalLahir: "2/25/2010",
    umur: 15,
    jenisKelamin: "Perempuan",
    agama: "Islam",
    kecamatan: "Plosoklaten",
    kelurahan: "Sumberagun",
    alamat: "Dsn. Karang",
    rt: "002",
    rw: "001",
    anakKe: 1,
    jumlahSaudara: 3,
    namaAyah: "SUMADI",
    namaIbu: "MISRI",
    ukuranBaju: "XL",
    ukuranSepatu: 42,
    waliAsuh: "Bu Erna & Eko Wahyudi"
  },
  {
    id: 3,
    nik: "3516125404090001",
    nomor: "3506080501110382",
    namaLengkap: "AMANDA AULIA PUTRI",
    tempatLahir: "Mojokerto",
    tanggalLahir: "4/14/2009",
    umur: 16,
    jenisKelamin: "Perempuan",
    agama: "Islam",
    kecamatan: "Puncu",
    kelurahan: "Puncu",
    alamat: "Dusun Puge",
    rt: "002",
    rw: "002",
    anakKe: 1,
    jumlahSaudara: 2,
    namaAyah: "Aman S.",
    namaIbu: "Siti Mutmain",
    ukuranBaju: "XL",
    ukuranSepatu: 41,
    waliAsuh: "Bu Erna & Eko Wahyudi"
  },
  {
    id: 4,
    nik: "3506155008090001",
    nomor: "3506151011180001",
    namaLengkap: "OSKA DEWI AGUSTINA",
    tempatLahir: "KEDIRI",
    tanggalLahir: "8/10/2009",
    umur: 15,
    jenisKelamin: "Perempuan",
    agama: "Islam",
    kecamatan: "Purwoasri",
    kelurahan: "Dawuhan",
    alamat: "Dsn Dawuha",
    rt: "04",
    rw: "02",
    anakKe: 1,
    jumlahSaudara: 3,
    namaAyah: "WANDI",
    namaIbu: "JAMIATIN",
    ukuranBaju: "M",
    ukuranSepatu: 37,
    waliAsuh: "Bu Erna & Eko Wahyudi"
  },
  {
    id: 5,
    nik: "3506016008090001",
    nomor: "3506012608210006",
    namaLengkap: "DANISA FAHMA SANIA",
    tempatLahir: "KEDIRI",
    tanggalLahir: "8/20/2009",
    umur: 15,
    jenisKelamin: "Perempuan",
    agama: "Islam",
    kecamatan: "Semen",
    kelurahan: "Bulu",
    alamat: "DSN. BULU",
    rt: "02",
    rw: "06",
    anakKe: 1,
    jumlahSaudara: 2,
    namaAyah: "MOH. SHOKENI",
    namaIbu: "ENI SETIYA",
    ukuranBaju: "L",
    ukuranSepatu: 37,
    waliAsuh: "Bu Erna & Eko Wahyudi"
  },
  {
    id: 6,
    nik: "3506014202100001",
    nomor: "3506010108190001",
    namaLengkap: "FIRDA AYU NATASYA",
    tempatLahir: "KEDIRI",
    tanggalLahir: "2/2/2010",
    umur: 15,
    jenisKelamin: "Perempuan",
    agama: "Islam",
    kecamatan: "Semen",
    kelurahan: "Bulu",
    alamat: "JL. SUNAN",
    rt: "3",
    rw: "4",
    anakKe: 1,
    jumlahSaudara: 3,
    namaAyah: "ANWAR SOL",
    namaIbu: "NINING LAI",
    ukuranBaju: "M",
    ukuranSepatu: 38,
    waliAsuh: "Bu Erna & Eko Wahyudi"
  },
  {
    id: 7,
    nik: "3506015105090001",
    nomor: "3506010412103889",
    namaLengkap: "ADELIA SUKMAWATI",
    tempatLahir: "KEDIRI",
    tanggalLahir: "5/11/2009",
    umur: 16,
    jenisKelamin: "Perempuan",
    agama: "Islam",
    kecamatan: "Semen",
    kelurahan: "Kedak",
    alamat: "KEDAK RT 1",
    rt: "1",
    rw: "3",
    anakKe: 1,
    jumlahSaudara: 2,
    namaAyah: "MATROCHI",
    namaIbu: "ARI SATUJU",
    ukuranBaju: "L",
    ukuranSepatu: 38,
    waliAsuh: "Bu Erna & Eko Wahyudi"
  },
  {
    id: 8,
    nik: "3506014211080003",
    nomor: "3506011206210015",
    namaLengkap: "WIWIN NOVITA SARI",
    tempatLahir: "KEDIRI",
    tanggalLahir: "11/2/2008",
    umur: 16,
    jenisKelamin: "Perempuan",
    agama: "Islam",
    kecamatan: "Semen",
    kelurahan: "Puhsarang",
    alamat: "DSN. NGLAN",
    rt: "3",
    rw: "6",
    anakKe: 2,
    jumlahSaudara: 2,
    namaAyah: "MUSILAN",
    namaIbu: "SUPARTI",
    ukuranBaju: "XL",
    ukuranSepatu: 40,
    waliAsuh: "Bu Erna & Eko Wahyudi"
  },
  {
    id: 9,
    nik: "3506016505090003",
    nomor: "3506010512100952",
    namaLengkap: "MEY NASILA",
    tempatLahir: "KEDIRI",
    tanggalLahir: "5/25/2009",
    umur: 16,
    jenisKelamin: "Perempuan",
    agama: "Islam",
    kecamatan: "Semen",
    kelurahan: "Selopanggu",
    alamat: "DSN. SELO",
    rt: "001",
    rw: "003",
    anakKe: 3,
    jumlahSaudara: 3,
    namaAyah: "DJANI",
    namaIbu: "KARTINEM",
    ukuranBaju: "XL",
    ukuranSepatu: 39,
    waliAsuh: "Bu Erna & Eko Wahyudi"
  },
  {
    id: 10,
    nik: "3506246210090001",
    nomor: "3506240701110382",
    namaLengkap: "ADINDA ORISIA ZIAMYSE",
    tempatLahir: "KEDIRI",
    tanggalLahir: "10/22/2009",
    umur: 15,
    jenisKelamin: "Perempuan",
    agama: "Islam",
    kecamatan: "Kayen Kidul",
    kelurahan: "Kayen Kidul",
    alamat: "DSN. KAYEN",
    rt: "001",
    rw: "002",
    anakKe: 2,
    jumlahSaudara: 2,
    namaAyah: "SUKARNI",
    namaIbu: "SUMINAH",
    ukuranBaju: "XL",
    ukuranSepatu: 38,
    waliAsuh: "Bu Erna & Eko Wahyudi"
  }
];
